### ISSUE TITLE
Not working on Ubuntu 21.04

### ISSUE THREAD

**Issue by itamarNov** [Maiqel/TP-Link-Archer-T4U-AC1300-Linux-driver-kernel-55#2]
errors while make...

**Comment by Maiqel** [comment]
Please check the newest version. There were big changes in 5.10. I just fixed the driver, and it's working with Ubuntu 20.04, kernel 5.8. 
If You would be so kind and tell me the `uname -a` for your machine that would be great. 
Please check if current version works for You and share the output, maybe I will have some time to try and tinker with it.
Best regards!

**Comment by itamarNov** [comment]
Thanks Maiqel,
I did not think using tp-link on ubuntu would be so bad as it is. Almost with any new version of ubuntu the dongle stop working...

Unfortunately, the new version did not work... :-(
I have attached 2 files:
- uname -a output
- terminal output
Thank you very much for your help,
ITAMAR
[uname.txt](https://github.com/Maiqel/TP-Link-Archer-T4U-AC1300-Linux-driver-kernel-55/files/6872212/uname.txt)
[output.txt](https://github.com/Maiqel/TP-Link-Archer-T4U-AC1300-Linux-driver-kernel-55/files/6872213/output.txt)

**Comment by Maiqel** [comment]
Hi! 
I checked Your output. I made some stupid mistakes...that should be fixed now.
However!! I did not have proper Kernel right now so the newest commit should only solve the errors I could read from your `output.txt` . This is kind of "I guess"... so if You can try to compile it with 1754a7e02f261b686765cd5a13fdf990df7243dc and give me feedback it would be great. 
If this still doesn't work  I'll try to setup some VM with kernel 5.11 and try to fixe it there.
Regards!

**Comment by Maiqel** [comment]
Edit: Previous commit wouldn't compile. Please check this one 523fcf21cc24a9eb97072d3d367060061277c1b4

**Comment by itamarNov** [comment]
Sorry, something is still wrong at the end:

Skipping BTF generation for /media/itamar/Data/itamar/tp-link_for_linux/2021-07-02/TP-Link-Archer-T4U-AC1300-Linux-driver-kernel-55-master/88x2bu.ko due to unavailability of vmlinux

Here is the new output file
[output.txt](https://github.com/Maiqel/TP-Link-Archer-T4U-AC1300-Linux-driver-kernel-55/files/6872750/output.txt)
 
thanks again :-)

**Comment by Maiqel** [comment]
Hmm... ok that is beyond my current knowledge, so I need to dig deeper. This might be the issue with newer kernels. 
However, it looks like you have linked the `88x2bu.ko` file. Does it exists? Did you try:
```
sudo cp 88x2bu.ko /lib/modules/[kernel version]/kernel/drivers/net/wireless/ 
sudo depmod -a 
sudo modprobe 88x2bu 
```
?

**Comment by Maiqel** [comment]
Well... I assume it works :D
